export const AUTH = "AUTH";
export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_DISMISS_ERROR = "AUTH_DISMISS_ERROR";
export const AUTH_LOGOUT = "AUTH_LOGOUT"; 
export const AUTH_CLEAR = "AUTH_CLEAR"; 
export const AUTH_INIT = "AUTH_INIT"; 
export const AUTH_TIMEOUT = "AUTH_TIMEOUT";

export const CREATE_MEDICINE = "CREATE_MEDICINE";
export const CREATE_MEDICINE_START = "CREATE_MEDICINE_START"; 
export const CREATE_MEDICINE_SUCCESS = "CREATE_MEDICINE_SUCCESS"; 
export const CREATE_MEDICINE_FAIL = "CREATE_MEDICINE_FAIL";
export const MEDICINES_REACHED = "MEDICINES_REACHED"; 
export const MEDICINES_DISMISS_ERROR = "MEDICINES_DISMISS_ERROR";
export const GET_MEDICINES = "GET_MEDICINES";
export const GET_MEDICINES_START = "GET_MEDICINES_START";
export const GET_MEDICINES_SUCCESS = "GET_MEDICINES_SUCCESS";
export const GET_MEDICINES_FAIL = "GET_MEDICINES_FAIL";
export const EDIT_MEDICINE_FIELDS = "EDIT_MEDICINE_FIELDS";
export const EDIT_MEDICINE = "EDIT_MEDICINE";
export const EDIT_MEDICINE_START = "EDIT_MEDICINE_START"; 
export const EDIT_MEDICINE_SUCCESS = "EDIT_MEDICINE_SUCCESS"; 
export const EDIT_MEDICINE_FAIL = "EDIT_MEDICINE_FAIL";
export const DELETE_MEDICINE = "DELETE_MEDICINE";

export const GET_MEDICINES_MARKET = "GET_MEDICINES_MARKET";
export const GET_MEDICINES_MARKET_START = "GET_MEDICINES_MARKET_START";
export const GET_MEDICINES_MARKET_SUCCESS = "GET_MEDICINES_MARKET_SUCCESS";
export const GET_MEDICINES_MARKET_FAIL = "GET_MEDICINES_MARKET_FAIL";
export const MARKET_MEDICINES_DISMISS_ERROR = "MARKET_MEDICINES_DISMISS_ERROR";
export const MARKET_PAGE_CHANGED = "MARKET_PAGE_CHANGED";
 
export const ORDER_MEDICINES = "ORDER_MEDICINES";
export const ORDER_MEDICINES_START = "ORDER_MEDICINES_START";
export const ORDER_MEDICINES_SUCCESS = "ORDER_MEDICINES_SUCCESS";
export const ORDER_MEDICINES_FAIL = "ORDER_MEDICINES_FAIL";

export const GET_ORDERS = "GET_ORDERS";
export const GET_ORDERS_START = "GET_ORDERS_START";
export const GET_ORDERS_SUCCESS = "GET_ORDERS_SUCCESS";
export const GET_ORDERS_FAIL = "GET_ORDERS_FAIL";
export const ORDERS_PAGE_CHANGED = "ORDERS_PAGE_CHANGED";
export const ORDER_DISMISS_ERROR = "ORDER_DISMISS_ERROR"; 


export const ADD_TO_CART = "ADD_TO_CART";
export const ADD_TO_CART_START = "ADD_TO_CART_START";
export const ADD_TO_CART_SUCCESS = "ADD_TO_CART_SUCCESS";
export const ADD_TO_CART_FAIL = "ADD_TO_CART_FAIL";
export const CLEAR_MODAL_DATA = "CLEAR_MODAL_DATA";

export const GET_CART = "GET_CART";
export const GET_CART_START = "GET_CART_START";
export const GET_CART_SUCCESS = "GET_CART_SUCCESS";
export const GET_CART_FAIL = "GET_CART_FAIL";

export const DELETE_CART_ITEM = "DELETE_CART_ITEM";
export const DELETE_CART_ITEM_START = "DELETE_CART_ITEM_START";
export const DELETE_CART_ITEM_SUCCESS = "DELETE_CART_ITEM_SUCCESS";
export const DELETE_CART_ITEM_FAIL = "DELETE_CART_ITEM_FAIL";

export const DELETE_CART = "DELETE_CART";